name: PR Comment

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: add commit to PR
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_REPO: ${{ github.repository }}
        run: |
          export body=$(curl ifconfig.co/json )
          export ip=$(echo $body | jq '.ip' )
          export country=$(echo $body | jq '.country' )
          gh pr comment ${{github.event.pull_request.number}} --body "runner ip: $ip, and country: $country"
